### ISSUE TITLE
Is content-addressing faster than location-addressing? 

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/faq#150]
Another way this could be phrased, I think, is this: Is searching through a merkledag data structure faster than a traditional filesystem? Or: How is IPFS faster than HTTP (and does that question make sense?)?

**Comment by warlord500** [comment]
content addressing and location addressing just ways to refer to a particular file. neither is necessarily slower or faster.  location addressing tells the computer where to find a file. content addressing says uses this file/data with this hash for this purpose. content doesn't tell you how to get said file. while location addressing does. 

with content addressing I can technically get the file from more places because as long as the file matches the hash I referring to the same data. so I could techinally get the file from my neighbor.
as long as check the hash,

however location addressing usually refers to a single location on the internet. It means to get said file I have to trust that server.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/is-content-addressing-faster-than-location-addressing/473
