### ISSUE TITLE
How does it compare to BitTorrent's Project Maelstrom?

### ISSUE THREAD

**Issue by vitorbaptista** [ipfs/faq#17]
N/T

**Comment by tommcintyre** [comment]
+1

**Comment by BillDStrong** [comment]
Bitorrent's Project Maelstrom is a system designed to handle downloading webpages and web content such as images and video. Or more precisely, it handles files in exactly the same way we currently handle files, with an added layer on top to benefit the server. 

It might benefit the user in the long run by ensuring access to content if the server is hit hard, but the server gets the most benefit, by reducing the costs to host the content. It is a form of content caching, only the user is part of the caching scheme, and has to opt in to it.

IPFS is a rethink on how data is transferred, and will ideally be transparent to the user. You should be able to go to a normal page, and that page will have a piece of javascript that will download parts of the page, or video or whatever over the IPFS system without interaction.

IPFS can be considered a caching scheme in rough terms, but it is a side effect of the design. What it actually is will make CDNs less necessary than they are today. Though they could use IPFS to broaden their market. 

IPFS is a filesystem while Bittorent is a download system. Fundamentally, this means that an IPFS aware application can issue a ipfs:\ call, just like a file:\ call, and receive a file. 

Lets give an example that does not work yet, but could. Say you are at a company and you use 3DS Max. Your colleague sent you his latest max file in email. You open it up, and notice it doesn't have any textures. 

In the Maelstrom model, you still have to contact your colleague about the textures. In IPFS, 3DS Max simply makes an ipfs call to the network, and the textures download automatically, and load when they are ready. It happens just like many games that download content dynamically. And you will only notice just a little bit of time from when the textures usually load.

To expand that example, in an VFX house where their is an approved texture set, and everyone must use those, just like version control, when the main textures are update by the designers, in the Maelstrom model all the textures would need to be downloaded, either by a torrent, or some in place system, or through version control.

With IPFS, version control is kinda builtin, and the next each artists uses the texture, ipfs can look for the latest version and automatically update behind the scenes.

All of this to say that they are fundamentally different models. And if Maelstrom sounds slightly more cumbersome than just using the web today,that is because it is, at least today.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-does-it-compare-to-bittorrents-project-maelstrom/411.
