### ISSUE TITLE
Using IPFS over a SOCKS proxy

### ISSUE THREAD

**Issue by mateon1** [ipfs/faq#185]
Recently, I've been on a network over which IPFS couldn't connect to anything, because of agressive outgoing port filtering, and the inability to punch through the NAT.
It did allow SSH (didn't filter port 22), so I'm wondering, whether it's possible to use IPFS over a SOCKS proxy, with an additional reverse-forwarded port for incoming connections.

An example solution would be:

```
ssh -R4001:0.0.0.0:4001 -D1080 user@remote

ipfs daemon --with-socks=localhost:1080
```

and

```
ipfs config Swarm.AdditionalAdvertised '["/ip4/remote/tcp/4001"]'
# and
ipfs swarm advertise /ip4/remote/tcp/4001
# (similarly to how `ipfs swarm filters` works)
```

Something along those lines should send everything through the localhost:1080 SOCKS proxy, and advertise /ip4/remote/tcp/4001/ipfs/QmPeerID to the swarm additionally to the regular addresses.

**Comment by ivar** [comment]
This would be interesting to know, as it might facilitate anonymization by running IPFS over Tor.

**Comment by jbenet** [comment]
- Since IPFS is just opening and using ports it is definitely configurable to use proxies or virtual networks with your OS networking stack. 
- I recommend the vpn / cjdns approach to things -- where it's not a single proxy, but all traffic is routed over a special network.
- It may or may not make sense to enable go-ipfs to follow proxy settings from a config -- not sure.
- I like the `Swarm.AdditionalAdvertised` idea. something like that makes sense. if you'd like to propose it, prototype the whole feature in https://github.com/ipfs/go-ipfs 
  - just as an issue in text is fine, just how it work in full. it can be tweaked and refined once it's being considered. 
- There will be native Tor support

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/using-ipfs-over-a-socks-proxy/440
