### ISSUE TITLE
Streaming data between nodes

### ISSUE THREAD

**Issue by andygough1974** [ipfs/faq#20]
Can IPFS connect 2 nodes and stream data between them.

**Comment by jbenet** [comment]
@andygough1974 could you describe the use case more? 

You can stream any data out of ipfs, for example:

```
hash=$(ipfs add <bigfile>)
ipfs cat $hash
```

will work across nodes, and stream. though, note that since the object is a merkledag, the standard unixfs datastructure has to hash the entire file before the root is known. A separate streaming datastructure, using an IPNS mutable pointer as a stream head can be used to start consuming a stream as it generates. It would look like this:

![](https://www.evernote.com/shard/s198/sh/e83aff21-dacc-42a1-a9d0-b99b04ac276c/950305bdc81f9f96c0d2bc163b470b51/deep/0/back-fwd-indexing.key.png)

---

If you're interested in sending data out of band-- meaning beyond the standard ipfs objects -- you can mount your own services/protocols onto ipfs nodes. See [Example: Making your own IPFS Service](http://gateway.ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmX6gcmX2vy2gs5dWB45w8aUNynEiqGhLayXySGb7RF2TM/readme.md)

We'll also have a simple pub/sub thing at some point.

**Comment by jbenet** [comment]
(btw, worth noting that the "indexing" data structure here does not need to be a linked list at all, it can be something better, like a binomial heap, etc.)

**Comment by chpio** [comment]
@jbenet the link in your 1. post is broken

**Comment by brutuscat** [comment]
@t128 [Making your own ipfs service](https://github.com/ipfs/examples/tree/master/examples/api/service#making-your-own-ipfs-service)

**Comment by chpio** [comment]
@brutuscat aha...

**Comment by jbenet** [comment]
>  @jbenet the link in your 1. post is broken

thanks fixed

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/streaming-data-between-nodes/475.
