### ISSUE TITLE
Why aren't DHT public key records signed?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/faq#220]
IPFS clients publish their public key on the DHT. Those records are not signed. Why not?

My guess: the validity of the public key can be checked by hashing it and comparing it to the peer ID. No signature required.

**Comment by Kubuxu** [comment]
Yes the identity directly corresponds to the public key, it is better signature then RSA could ever give. Other DHT records (provider) are not currently signed due to size and computation costs of RSA. We are planning switch to x25519 crypto which will enable us to sign those records fast and cheaply

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/why-arent-dht-public-key-records-signed/341
