### ISSUE TITLE
Characteristics of extremely short-lived nodes?

### ISSUE THREAD

**Issue by markikollasch** [ipfs/faq#221]
What behavior can be expected of a node that is started up for the purposes of immediately downloading and pinning a single file, and runs only for a few minutes, after which it goes offline and deletes the file?

**Comment by RichardLitt** [comment]
I'm not sure I understand. I would expect that some people will do this; but the overall network will have long-standing nodes and data with multiple peers holding it. If the file is held by another peer, it will still be available on the system; otherwise, it won't be, although you could easily add it again and it would still be content addressable at the same hash.

**Comment by markikollasch** [comment]
I'm thinking about intermediate steps that can use ipfs without mainstream adoption among people who don't know or care how content gets to them. One use case that came to mind is using it as a sort of CDN for large popular static web content: the user browses to a page that instantiates a Javascript ipfs client, which acquires the actual content, exposes it to the page it once it is downloaded, and continues to host it while the page is open. I'm wondering how pathological that would be.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/characteristics-of-extremely-short-lived-nodes/337.
