### ISSUE TITLE
How to be a nice guy? (Filecoin & public gateway alternatives for seeding?)

### ISSUE THREAD

**Issue by Beanow** [ipfs/faq#258]
Since Filecoin isn't running yet, and a public gateway requires you to persuade users to use your HTTP(S) address.

What is a good way to configure your node to actively try and reinforce the IPFS network?
Or is there a dedicated utility for this?

I have a few TB of fault-tolerant disk space to spare on a prototyping server of mine with a 100/100mbit connection. Once it's there it would be great to run Filecoin on that. But for the time being I'd like it to simply help out the network the best way it can.

What I presume would be needed:
- Start discovering data appearing in want lists, and hoard it to fill up those TBs without pinning (which I hope would automatically strike a balance between rare and popular hashes since those will show up either longer or most often).
- Set a more lenient ratio for peer reputation.
- Rate limit how much data you slurp from peers so you don't saturate their bandwidth and make the network perform worse instead of better.
- Make the garbage collection as lazy as possible, preserving the largest have list we can fit on remaining disk space.

**Comment by Beanow** [comment]
On the same line of thought. Are there any good blocklists like #9 available right now or that I should keep an eye on for the near future? Would be great if my well intended server doesn't become a hotbed of malware and illegal content.

**Comment by flyingzumwalt** [comment]
That's a very good question @Beanow. We're trying to migrate questions like yours to https://discuss.ipfs.io because the site provides a better venue for community discussion. (Github issues are designed for tracking work and making decisions, which makes it hard for open-ended discussions to unfold.) Would you be willing to re-post there?

My personal inclination, which I can also re-post on discuss.ipfs.io, is to focus on finding datasets that you personally care about or find inspiring (ie. data.gov, [wikipedia](https://github.com/ipfs/distributed-wikipedia-mirror/blob/master/snapshot-hashes.yml), or anything you find compelling). If those data are not on IPFS yet, add them. If they're already on IPFS, pin a copy on your node. Either way, pass around the hashes/links.

**Comment by Beanow** [comment]
Fair enough. Moved it here:
https://discuss.ipfs.io/t/how-to-be-a-nice-guy-filecoin-public-gateway-alternatives-for-seeding/233
