### ISSUE TITLE
is ipfs fit for personal blog pages

### ISSUE THREAD

**Issue by goog** [ipfs/faq#30]

**Comment by jbenet** [comment]
absolutely

**Comment by goog** [comment]
for static html page files ? is there only one gateway?   how to configure it on my linode

**Comment by jbenet** [comment]
@goog i'd recommend 
- run an ipfs node on your linode. can do it with docker and the dockerfile
- use `ipfs add -r path/to/your/blog` in your computer
- use `ipfs pin add -r <hash-you-got>` in your linode

**Comment by ghost** [comment]
Yes it is, we're even hosting the ipfs.io website out of IPFS.

@giodamelio wrote a tutorial the other day: https://ipfs.io/ipfs/QmdPtC3T7Kcu9iJg6hYzLBWR5XCDcYMY7HV685E3kH3EcS/2015/09/15/hosting-a-website-on-ipfs/

For IPNS a few limitations apply, for the time being: https://github.com/ipfs/go-ipfs/issues/1716#issuecomment-141140667

**Comment by windemut** [comment]
So, where can one find any of these ipfs web sites? Is there anything at all to browse? Google searches produce nothing, this thread is the closest to finding content that I could get. Seems like a massive PR problem, to me.

**Comment by jbenet** [comment]
@windemut 
- First and foremost you should be aware that IPFS is _an alpha_ and targeted at developers.
- The link in @lgierth's post above is one.
- https://ipfs.io is another, hosted through ipfs itself, exposed through the gateway and with dnslink.
- If you'd like to see the content your node becomes aware of, i suggest you look at the hashes going through the dht in your node. this will require getting comfortable recompiling the code, adding logging, etc. (we'll add event hooks for this eventually). 

> Google searches produce nothing

Do you realize that IPFS is a different protocol than HTTP and that Google does not index IPFS yet?

You [_can_ find _some_ links on Google](http://lmgtfy.com/?q=inurl%3A%22ipfs.io%2Fipfs%2F%22) to some sites / content on our gateway, but note that these need to be linked to from _other_ websites outside our gateway. Moreover, google has been penalizing our gateway because -- since it is under the same domain -- it looks like one site linking to itself a lot.

We currently browse IPFS content on _web browsers that do not understand IPFS_ (all of them) via an HTTP-to-IPFS gateway, included in go-ipfs, which means ipfs links _for now_ look like: "http://<gateway-domain>/<ipfs-link>" such as: 
- https://ipfs.io/ipns/chat.ipfs.io
- https://ipfs.io/ipfs/Qmbm8matKreFd1nDwA3CWWCMauMcSEJNz1NVJ4ApEzJbhp
- http://localhost:8080/ipfs/Qmbm8matKreFd1nDwA3CWWCMauMcSEJNz1NVJ4ApEzJbhp

>  this thread is the closest to finding content that I could get. Seems like a massive PR problem, to me.

Of course, all of this should be easier to find, but since it isn't yet, you'll have to search more. Giving up like this when so many others find it just fine makes this seem a bit [help vampirish](http://slash7.com/2006/12/22/vampires/).

Some examples, coming from our community:
- https://ipfs.io/ipfs/QmdPtC3T7Kcu9iJg6hYzLBWR5XCDcYMY7HV685E3kH3EcS/2015/09/15/hosting-a-website-on-ipfs/
- https://ipfs.io/ipfs/QmdC4sh51AkV9v9dam58TBrXL7cmT8v4sjdpzYsdkK3raA/examples/flatland/
- https://ipfs.io/ipfs/QmTJHuzG3mjgmvcfvTU4ykWXwD4QjA5aCk6QsU4BPaD8Hh
- https://ipfs.io/ipfs/QmSc2NAfY5ho2gTLkC87QZWJU3qVi1qYBFRG589znncNE3
- https://ipfs.io/ipfs/QmR7GSQM93Cx5eAg6a6yRzNde1FQv7uL6X1o4k7zrJa3LX/ipfs.draft3.pdf
- https://ipfs.io/ipfs/QmY1sJAqkxfJ6YbMaFBvs15hsmmbeBTKPe6jyd8GSZMtpP
- http://chat.ipfs.io/ -> https://ipfs.io/ipns/chat.ipfs.io/ --> https://ipfs.io/ipfs/Qmbm8matKreFd1nDwA3CWWCMauMcSEJNz1NVJ4ApEzJbhp
- http://blog.daviddias.me/ -- https://ipfs.io/ipns/daviddias.me/ 
- Every single neocities site is also on ipfs, for example:
  - https://neocities.org/site/dragonquest
  - http://ciqfgjwsiqm7yggxhybph5aiziquusj6jeet2hpxxd7iygw5vhgrpjy.ipfs.neocitiesops.net/ on neocities' gateway
  - on our HTTP gateway (beware XSS!): https://ipfs.io/ipfs/QmTwEt89e6y3bRNMuZwhZHk7JjoeiYbqcASYHh6gkgnCoQ/
  - on your HTTP gateway, if you're running ipfs locally: http://localhost:8080/ipfs/QmTwEt89e6y3bRNMuZwhZHk7JjoeiYbqcASYHh6gkgnCoQ/
- Read more about publishing a site (including dnslink trick) here: https://github.com/diasdavid/ipscend/

And please, next time, try searching more and asking a bit more nicely. If you don't, you won't get much help around here.

**Comment by windemut** [comment]
Thanks for the patient reply, jbenet.

First of all, I apologize if my comments sounded impatient, it reflects my frustration as an excited new wannabe user, and the tone was ill-considered.

I do, of course, realize that Google does not index IPFS, but I was expecting to find some out-of-channel references into IPFS, a portal, perhaps. Neither the web-site, nor the webgui seem to have that, nor could I find it anywhere else. There are very nice tutorials on how to download things from the command-line, like the cat picture, but ultimately the new Web should be browsable, like the old one, or not? 

If I interpret your answer correctly, the IPFS developers think that the system is not ready for casual browsing because it is still in alpha. That makes sense, but is a little incongruent with the inviting tone of the main web-page.

Thank you for the collection of links in your reply, it is pretty much what I was looking for. I would suggest polishing it up and linking to it from both the web-site and the WebGui. That would help bring curious users in and generate interest in creating content, once you are comfortable with that.

I also now understand better that all ipfs links are channelled through "https://ipfs.io/" to accomodate browsers. There is, though, the Firefox plugin, which I installed. It seems to work, but, alas, It, too, does not seem to come with a lot of working links to try it on.

Lastly, I hope this message sounds a little better than the last, and let me express my unreserved admiration for the project. I do think it has the potential to revolutionize the Internet.

**Comment by windemut** [comment]
Just tried the 'inurl:"ipfs.io/ipfs/"' you googled for me. That's a great way to search for ipfs links I did not think of. Awesome!

**Comment by jbenet** [comment]
@windemut :) great! :+1: and thanks!

agree it should be easier for users to find this content. maybe you can find a good spot to place this. or seed a blog post with some content to try.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/is-ipfs-fit-for-personal-blog-pages/331
