### ISSUE TITLE
Why not import/export tar archives to/from unixfs?

### ISSUE THREAD

**Issue by Stebalien** [ipfs/faq#59]
Tar is just a portable read-only filesystem format so why does `ipfs tar add/cat` import into and export from a special tar dag instead of just using unixfs (also a portable read-only filesystem format)?

**Comment by jbenet** [comment]
Because that way you get really good dedup within tars. (and can even mount tars). it's an example datastructure. this is pre-work towards `car`, an archive fmt we're making

**Comment by Stebalien** [comment]
Sorry, my question was unclear. Why not _extract_ the tar into unixfs. That is, why write another merkeldag format for read-only filesystems when you already have one.

**Comment by Stebalien** [comment]
Is this to work around the lack of metadata (permissions etc.) storage in unixfs?

**Comment by jbenet** [comment]
> Is this to work around the lack of metadata (permissions etc.) storage in unixfs?

precisely-- it was a quick hack meanwhile we work on unixfs. but it ended up being pretty useful

it's also useful to have native support for tars, so that in the future we can import regular unix filesystems and yet dedup tars and look into them. And still be able to reproduce the exact same fs on the way out.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/why-not-import-export-tar-archives-to-from-unixfs/294.
