### ISSUE TITLE
File-chunk identification possibility

### ISSUE THREAD

**Issue by shalnoff** [ipfs/faq#85]
Is it possible to identify the file that chunk is owned (and vice versa)?

**Comment by RichardLitt** [comment]
I'm not sure. @diasdavid @whyrusleeping what do you think?

**Comment by whyrusleeping** [comment]
@shalnoff could you clarify what you mean?

**Comment by daviddias** [comment]
@shalnoff if your question is 'given a chunk, can I identify the file it belongs to, without any other information at all', the answer is no, you can't, that would violate the principle of a DAG.

**Comment by mcast** [comment]
> @shalnoff if your question is 'given a chunk, can I identify the file it belongs to, without any other information at all', the answer is no, you can't, that would violate the principle of a DAG.

I would only add, "...unless you have some extra information".  Would these methods work?
1. fetching the chunk's data, recognising some distinctive feature of its encoding. _e.g._ it's plain text, or gzipped text with a convenient block start; take five words and put them into a search engine to get the original.
2. enumerate (#155) a large enough swathe to discover (some of) the chunk's parents.
3. be in possession of some kind of reverse-lookup index, constructed from such enumeration

In a [different chunking system, which could ride ipfs](http://www.madore.org/~david/misc/freespeech.html) it is by design impossible to identify chunks.

**Comment by shalnoff** [comment]
Clear, that's what I'd like to clarify. Thank you (sorry for late reply)

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/file-chunk-identification-possibility/353.
