### ISSUE TITLE
`ipfs name publish` to same hash from separate computers

### ISSUE THREAD

**Issue by doesntgolf** [ipfs/faq#88]
I'm wondering if publishing to the same IPNS hash from separate computers is 1) doable now, 2) not yet doable but planned, or 3) not possible or not planned.

**Comment by fazo96** [comment]
It would be number two as far as I know :+1: It's planned but not doable yet

**Comment by whyrusleeping** [comment]
this is planned, and should be implemented fairly soon (many other things will depend on this capability) https://github.com/ipfs/specs/tree/master/keystore

**Comment by RichardLitt** [comment]
@whyrusleeping What is the status on this? Curious.

**Comment by wigy-opensource-developer** [comment]
We need this feature for an open source project we are working on atm. Since there seems to be little progression on this, we would like to help implementing parts of it on our fork.

Our use-case is that the private key used for signing the IPNS record is **not shared** with the IPFS node that republishes the record. For that we need to
- Allow the IPNS record author ID to be different from the peer ID of the IPFS node (requires some refactoring of the existing code that would be needed for the keystore feature anyway)
- Add an API command to publish an IPNS record that was already signed by the caller
  - the IPFS node maintains a list of allowed author IDs and rejects to republish records written by other authors
  - if the IPFS node finds a record with greater sequence number, it reports an error including the highest sequence number found on the network

@whyrusleeping Would these changes be something that you would be happy to merge back?

**Comment by Kubuxu** [comment]
@wigy-opensource-developer there is separate program that can be used for that: https://github.com/whyrusleeping/ipns-pub
and you can use `ipns-key` program to generate key-pair. This can be the workaround for now.

**Comment by wigy-opensource-developer** [comment]
Thanks, I have already seen those tools. Our use case cannot assume that the author has internet access every 12 hours to republish the IPNS record. Also, we cannot give the private key to the node that has continuous internet access. Correspondingly, we need to separate the responsibilities of signing and publishing the record.

**Comment by ghost** [comment]
@wigy-opensource-developer we have IPRS (record system) in the works on and off, which will allow you to pin other nodes' IPNS records and should benefit your use case. It's likely not gonna happen in the few weeks left this year :(

But we're on it and it would be great to have your feedback: https://github.com/ipfs/specs/search?q=iprs&type=Issues&utf8=%E2%9C%93

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/ipfs-name-publish-to-same-hash-from-separate-computers/288
