### ISSUE TITLE
How permanent is data stored on IPFS?

### ISSUE THREAD

**Issue by randomshinichi** [ipfs/faq#93]
In the whitepaper it says 'Objects are permanent'.

How can they be if there is no guarantee that all the 256KB objects that make up my original file are on other people's nodes? What if they ipfs repo gc? There has been talk about using IPFS as a versioned backup system but is my data really going to live forever out there?

Also, if I'm storing other people's objects, then I could also read the data in them, right?

**Comment by ghost** [comment]
Permanence != Persistance

Permanence is about naming: content-addressing makes it so that an object's name will always be the same. The "permanent web" is a web of links between objects with permanent names. The names are always the same, and thus the links won't break.

Persistance is about storage: IPFS itself currently handles this by means of "pinning", which excludes an object and its children from garbage collection within one IPFS node. In the future there will be more involved ways of managing persistance. One of them is Filecoin ([paper](http://filecoin.io/filecoin.pdf)), and there a couple of concrete ideas for an ipfs-cluster tool (ipfs/notes#58).

**Comment by ghost** [comment]
This one is also related: [Replication on IPFS -- Or, the Backing-Up Content Model](https://github.com/ipfs/faq/issues/47)

**Comment by jbenet** [comment]
To add to this, the way you should think about it is this:

Basics: 
- read [Replication on IPFS -- Or, the Backing-Up Content Model](https://github.com/ipfs/faq/issues/47)
- as long as _anybody_ is willing to continue expending energy to maintain an object online, then that object is permanent. if _nobody_ is willing to do that, then the object naturally cannot be transferred ad transferring requires energy expenditure.
- this translates naturally to having both the traditional Web model, where publishers are also _servers_ of the content.
- but also includes that all readers share bandwidth costs (while caching)
- and those readers who choose to keep the object too then become _servers_ too, and as important as the original one.

Advanced Collaboration + Replication:
- Now, this of course means that you can organize peers into networks that share the cost of backing each others' content up, similar to how many other p2p systems work.
- we are writing [ipfs-cluster](https://github.com/ipfs/notes/issues/58) to improve how this will work.
- in IPFS we have things like [pincoop](https://github.com/victorbjelkholm/pincoop) and [ipfs-persistence-consortium](https://github.com/pipermerriam/ipfs-persistence-consortium) -- which aim to create collaborative pinning networks
- But -- for those who do not want to maintain their own infrastructure -- the long term solution is to solve this with markets, where users can be at either end of the "resource contribution or resource consumption" spectrum, as will be seen in [Filecoin](http://filecoin.io) and [Ethereum](http://ethereum.org).

**Comment by RichardLitt** [comment]
Keeping this open so that it is more easily finable in the FAQ. Thanks. :)

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-permanent-is-data-stored-on-ipfs/354.
